import type { Book } from "./types";

export const books: Book[] = [
  {
    title: "Meditations",
    author: "Marcus Aurelius",
    cover: {
      src: "/books/meditations.jpeg",
      alt: "Meditations cover",
      width: 775,
      height: 1240,
    },
    readYear: "reading",
    genres: ["Philosophy", "Self-Help"],
    featured: true,
  },
  {
    title: "Beyer On Speed: New Strategies for Racetrack Betting",
    author: "Andrew Beyer",
    cover: {
      src: "/books/beyer-on-speed-new-strategies-for-racetrack-betting.jpg",
      alt: "Beyer On Speed: New Strategies for Racetrack Betting cover",
      width: 826,
      height: 1240,
    },
    readYear: 2026,
    genres: ["Sports Analytics"],
    featured: false,
  },
  {
    title: "Picking Winners: A Horseplayer's Guide",
    author: "Andrew Beyer",
    cover: {
      src: "/books/picking-winners-a-horseplayer-s-guide.jpg",
      alt: "Picking Winners: A Horseplayer's Guide cover",
      width: 828,
      height: 1240,
    },
    readYear: 2026,
    genres: ["Sports Analytics"],
    featured: false,
  },
  {
    title: "Inside the Black Box",
    author: "Rishi K. Narang",
    cover: {
      src: "/books/inside-the-black-box.webp",
      alt: "Inside the Black Box cover",
      width: 800,
      height: 1183,
    },
    readYear: 2026,
    genres: ["Trading", "Investing"],
    note: "About Quantitative Trading",
    featured: false,
  },
  {
    title: "We Are the Nerds",
    author: "Christine Lagorio-Chafkin",
    cover: {
      src: "/books/we-are-the-nerds.webp",
      alt: "We Are the Nerds cover",
      width: 800,
      height: 1220,
    },
    readYear: 2026,
    genres: ["Nonfiction", "Business"],
    featured: false,
  },
  {
    title: "Chancing It",
    author: "Robert Matthews",
    cover: {
      src: "/books/chancing-it.webp",
      alt: "Chancing It cover",
      width: 800,
      height: 1196,
    },
    readYear: 2026,
    genres: ["Data Science", "Nonfiction"],
    featured: false,
  },
  {
    title: "Superforecasting",
    author: "Philip E. Tetlock",
    cover: {
      src: "/books/superforecasting.webp",
      alt: "Superforecasting cover",
      width: 800,
      height: 1236,
    },
    readYear: 2026,
    genres: ["Psychology", "Data Science"],
    featured: false,
  },
  {
    title: "巴菲特的勝券在握之道",
    author: "羅伯特‧海格斯壯",
    cover: {
      src: "/books/book-9573278812.jpg",
      alt: "巴菲特的勝券在握之道 cover",
      width: 800,
      height: 1070,
    },
    readYear: 2026,
    genres: ["Investing"],
    featured: false,
  },
  {
    title: "Outliers",
    author: "Malcolm Gladwell",
    cover: {
      src: "/books/outliers.webp",
      alt: "Outliers cover",
      width: 800,
      height: 1201,
    },
    readYear: 2025,
    genres: ["Psychology", "Nonfiction"],
    featured: false,
  },
  {
    title: "The Wealth Ladder",
    author: "Nick Maggiulli",
    cover: {
      src: "/books/the-wealth-ladder.webp",
      alt: "The Wealth Ladder cover",
      width: 800,
      height: 1208,
    },
    readYear: 2025,
    genres: ["Personal Finance"],
    featured: false,
  },
  {
    title: "A Mind for Numbers",
    author: "Barbara Oakley",
    cover: {
      src: "/books/a-mind-for-numbers.webp",
      alt: "A Mind for Numbers cover",
      width: 800,
      height: 1200,
    },
    readYear: 2025,
    genres: ["Self-Help", "Psychology"],
    featured: false,
  },
  {
    title: "Deep Work",
    author: "Cal Newport",
    cover: {
      src: "/books/deep-work.webp",
      alt: "Deep Work cover",
      width: 800,
      height: 1208,
    },
    readYear: 2025,
    genres: ["Productivity"],
    featured: false,
  },
  {
    title: "How to Become a Straight-A Student",
    author: "Cal Newport",
    cover: {
      src: "/books/how-to-become-a-straight-a-student.webp",
      alt: "How to Become a Straight-A Student cover",
      width: 800,
      height: 1234,
    },
    readYear: 2025,
    genres: ["Productivity", "Self-Help"],
    featured: false,
  },
  {
    title: "The Bitcoin Standard",
    author: "Saifedean Ammous",
    cover: {
      src: "/books/the-bitcoin-standard.webp",
      alt: "The Bitcoin Standard cover",
      width: 800,
      height: 1184,
    },
    readYear: 2025,
    genres: ["Investing", "Nonfiction"],
    featured: false,
  },
  {
    title: "The First World War: A Very Short Introduction",
    author: "Michael Howard",
    cover: {
      src: "/books/the-first-world-war-a-very-short-introduction.webp",
      alt: "The First World War: A Very Short Introduction cover",
      width: 800,
      height: 1269,
    },
    readYear: 2025,
    genres: ["Nonfiction"],
    featured: false,
  },
  {
    title: "小王子的領悟",
    author: "周保松",
    cover: {
      src: "/books/book-a6e5dc0768.webp",
      alt: "小王子的領悟 cover",
      width: 800,
      height: 1035,
    },
    readYear: 2025,
    genres: ["Nonfiction"],
    featured: false,
  },
  {
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    cover: {
      src: "/books/the-little-prince.webp",
      alt: "The Little Prince cover",
      width: 800,
      height: 1144,
    },
    readYear: 2025,
    genres: ["Fiction"],
    featured: false,
  },
  {
    title: "How to Win the Premier League",
    author: "Ian Graham",
    cover: {
      src: "/books/how-to-win-the-premier-league.webp",
      alt: "How to Win the Premier League cover",
      width: 800,
      height: 1228,
    },
    readYear: 2025,
    genres: ["Sports Analytics", "Data Science"],
    featured: false,
  },
  {
    title: "Four Thousand Weeks",
    author: "Oliver Burkeman",
    cover: {
      src: "/books/four-thousand-weeks.webp",
      alt: "Four Thousand Weeks cover",
      width: 800,
      height: 1233,
    },
    readYear: 2025,
    genres: ["Productivity", "Self-Help"],
    featured: false,
  },
  {
    title: "Statistics: A Very Short Introduction",
    author: "David J. Hand",
    cover: {
      src: "/books/statistics-a-very-short-introduction.webp",
      alt: "Statistics: A Very Short Introduction cover",
      width: 800,
      height: 1254,
    },
    readYear: 2025,
    genres: ["Data Science", "Nonfiction"],
    featured: false,
  },
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    cover: {
      src: "/books/harry-potter-and-the-sorcerers-stone.jpg",
      alt: "Harry Potter and the Sorcere's Stone cover",
      width: 800,
      height: 1254,
    },
    readYear: 2025,
    genres: ["Fiction"],
    featured: false,
  },
  {
    title: "The Psychology of Money",
    author: "Morgan Housel",
    cover: {
      src: "/books/the-psychology-of-money.webp",
      alt: "The Psychology of Money cover",
      width: 800,
      height: 1236,
    },
    readYear: 2025,
    genres: ["Personal Finance", "Psychology"],
    featured: false,
  },
  {
    title: "How to Win Friends & Influence People",
    author: "Dale Carnegie",
    cover: {
      src: "/books/how-to-win-friends-influence-people.webp",
      alt: "How to Win Friends & Influence People cover",
      width: 800,
      height: 1200,
    },
    readYear: 2025,
    genres: ["Self-Help", "Psychology"],
    featured: false,
  },
  {
    title: "Just Keep Buying",
    author: "Nick Maggiulli",
    cover: {
      src: "/books/just-keep-buying.webp",
      alt: "Just Keep Buying cover",
      width: 800,
      height: 1236,
    },
    readYear: 2025,
    genres: ["Personal Finance", "Investing"],
    featured: true,
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    cover: {
      src: "/books/atomic-habits.webp",
      alt: "Atomic Habits cover",
      width: 800,
      height: 1208,
    },
    readYear: 2025,
    genres: ["Self-Help", "Psychology"],
    featured: true,
  },
  {
    title: "One Up On Wall Street",
    author: "Peter Lynch",
    cover: {
      src: "/books/one-up-on-wall-street.webp",
      alt: "One Up On Wall Street cover",
      width: 800,
      height: 1219,
    },
    readYear: 2025,
    genres: ["Investing"],
    featured: false,
  },
  {
    title: "實踐價值投資的真諦",
    author: "鍾記",
    cover: {
      src: "/books/book-21b7e809f6.webp",
      alt: "實踐價值投資的真諦 cover",
      width: 800,
      height: 1120,
    },
    readYear: 2024,
    genres: ["Investing"],
    featured: false,
  },
  {
    title: "The Bogleheads' Guide to Investing",
    author: "Taylor Larimore",
    cover: {
      src: "/books/the-bogleheads-guide-to-investing.webp",
      alt: "The Bogleheads' Guide to Investing cover",
      width: 800,
      height: 1194,
    },
    readYear: 2024,
    genres: ["Investing", "Personal Finance"],
    featured: false,
  },
  {
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    cover: {
      src: "/books/rich-dad-poor-dad.webp",
      alt: "Rich Dad Poor Dad cover",
      width: 800,
      height: 1200,
    },
    readYear: 2024,
    genres: ["Personal Finance"],
    featured: false,
  },
];

export const featuredBooks = books.filter((book) => book.featured);
